#!/bin/sh

set -e

if [ "$OS_NAME" = "ubuntu-latest" ]; then
    wget https://github.com/dcreager/buzzy/releases/download/0.6.0/ubuntu.trusty.buzzy_0.6.0_amd64.deb -O buzzy.deb
    sudo dpkg -i buzzy.deb
fi
